repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-xml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: forbid-submodules
      - id: mixed-line-ending
      - id: no-commit-to-branch
      - id: trailing-whitespace

  - repo: https://github.com/thibaudcolas/pre-commit-stylelint
    rev: v16.23.0
    hooks:
      - id: stylelint
        args: [--fix]
        additional_dependencies:
          - stylelint@16.19.1
          - stylelint-config-standard-scss@14.0.0
          - stylelint-config-clean-order@7.0.0

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        types_or: [yaml, json, xml, markdown, scss, javascript]

  - repo: https://github.com/woodruffw/zizmor-pre-commit
    rev: v1.11.0
    hooks:
      - id: zizmor
