repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-xml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: forbid-submodules
      - id: mixed-line-ending
      - id: no-commit-to-branch
      - id: trailing-whitespace

  - repo: https://github.com/awebdeveloper/pre-commit-stylelint
    rev: "4200758"
    hooks:
      - id: stylelint
        additional_dependencies:
          [
            "stylelint@15.11.0",
            "stylelint-config-standard-scss@11.0.0",
            "stylelint-config-clean-order@5.2.0",
            "stylelint-selector-bem-pattern@3.0.1",
          ]
        args: ["--fix"]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        types_or: [yaml, json, xml, markdown, scss, javascript]
