name: CI
permissions: {}
on:
  push:

jobs:
  build-scss:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          persist-credentials: false

      - name: Set up node
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0

      - name: Install node dependencies
        run: npm install sass

      - name: Build scss
        run: npm run build
