name: Source safety
permissions: {}
on:
  pull_request:
  push:
jobs:
  secrets:
    name: Check for secrets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          persist-credentials: false
      - uses: nationalarchives/tdr-github-actions/.github/actions/run-git-secrets@af4df0b5325dcd5277e8291745c9e5a7d2e68d79
